# Dockerfile for the back-end micro-service

FROM python:3

RUN useradd --create-home test_user
USER test_user
WORKDIR /home/test_user

RUN pip install requests
COPY backend.py .

CMD [ "python3", "backend.py" ]